# This is a basic workflow to help you get started with Actions

name: Deploy Model Evaluation APP
on:
  push:
	branches:
  	- main

jobs:
  deploy:
	runs-on: ubuntu-latest

	steps:
  	- name: Checkout code
    	uses: actions/checkout@v3

  	- name: Set up Python
    	uses: actions/setup-python@v4
    	with:
      	python-version: '3.9'  # Specify the Python version

  	- name: Install dependencies
    	run: |
      	python -m pip install --upgrade pip
      	pip install panel holoviews bokeh
      	pip install -r requirements.txt  # Optional: if you have additional dependencies listed

  	- name: Start HoloViz app
    	run: |
      	nohup panel serve class_app.py --address 0.0.0.0 --port 5006 &

  	- name: Verify app is running
    	run: |
      	sleep 5
      	curl --retry 5 --retry-delay 10 --fail http://localhost:5006 || exit 1

  	- name: Notify on success
    	run: echo "HoloViz app deployed successfully."

  deploy_to_server:
	needs: deploy
	runs-on: ubuntu-latest

	steps:
  	- name: Checkout code
    	uses: actions/checkout@v3

  	- name: Deploy to server (optional)
    	run: |
      	echo "Add commands to deploy the app to a production server or containerize it."

  	- name: Notify on success
    	run: echo "App successfully deployed to production."
